name: Build Pico SDK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Clone and Build Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Package Pico SDK
      run: |
        zip -r pico-sdk.zip pico-sdk

    - name: Create Release and Upload Asset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if ! gh release view v1.0.0 &>/dev/null; then
          echo "Creating new release v1.0.0"
          gh release create v1.0.0 --title "Release v1.0.0" --notes "Initial release" --generate-notes
        else
          echo "Release v1.0.0 already exists"
        fi
        
        PICO_SDK_VERSION=$(cd pico-sdk && git rev-parse --short HEAD)
        gh release upload v1.0.0 pico-sdk.zip --clobber
        gh release edit v1.0.0 --notes "Pico SDK version: ${PICO_SDK_VERSION}"