name: Build Psiphon Tunnel Core (x86)

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib
        
    - name: Clone psiphon-tunnel-core
      run: |
        git clone https://github.com/Psiphon-Labs/psiphon-tunnel-core.git
        
    - name: Build
      env:
        GOARCH: 386
        GOOS: linux
      run: |
        cd psiphon-tunnel-core/ConsoleClient
        go build -v -o psiphon-tunnel-core-x86
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: psiphon-tunnel-core-x86
        path: psiphon-tunnel-core/ConsoleClient/psiphon-tunnel-core-x86
