name: Combine Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  combine-releases:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Release if not exists and Combine Assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if ! gh release view v1.0.0 &>/dev/null; then
          echo "Creating new release v1.0.0"
          gh release create v1.0.0 --title "Release v1.0.0" --notes "Combined release" --generate-notes
        else
          echo "Release v1.0.0 already exists"
        fi

        # Download releases
        gh release download v1.0.0

        # Create all.zip
        zip -r all.zip *.zip

        # Split file if larger than 2GB
        if [ $(stat -c%s "all.zip") -gt 2147483648 ]; then
          split -b 2G all.zip all.zip.part_
          for part in all.zip.part_*; do
            gh release upload v1.0.0 "$part" --clobber
          done
        else
          gh release upload v1.0.0 all.zip --clobber
        fi

        # Update Description
        gh release edit v1.0.0 --notes "Đây là bản release kết hợp của các bản build QEMU, Pico SDK và MicroPython"