name: Combine Releases

on:
  workflow_dispatch:

permissions:
  contents: write
  contents: read

jobs:
  combine-releases:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Release if not exists and Combine Assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if ! gh release list | grep -q "v1.0.0"; then
          echo "Creating new release v1.0.0"
          gh release create v1.0.0 --title "Release v1.0.0" --notes "Combined release" --generate-notes
        else
          echo "Release v1.0.0 already exists"
        fi

        # Download releases
        gh release download v1.0.0

        # Create all.tar.gz
        tar -czf all.tar.gz *.tar.gz

        # Upload Combined Asset and Update Description
        gh release upload v1.0.0 all.tar.gz --clobber
        gh release edit v1.0.0 --notes "Đây là bản release kết hợp của các bản build QEMU, Pico SDK và MicroPython"